export function getProtfolioProjects() {
  return [
    { 
      id: 1, 
      title: 'The Art Collector Private Residence', 
      type: 'Private Residence',
      architects: ['Zaher Bissar'],
      year: 2022,
      location: 'Riyadh',
      description : `One of the first assignments for us is to set the inspiration for the project; we invest a tremendous amount of time seeking inspiration from our client’s lifestyle and personal tastes. Aware of our client’s interest in fine art, we have selected masterpieces from the most prestigious galleries in the world. The warm and textured wooden high walls has created the perfect background for these art pieces.
      This project with fortunate high ceilings was transformed into a hidden museum in a private home.`,      
      banner:'/images_v1/projects/portfolio/the_collector_private_residence/banners/banner1.jpg',
      thumbnail: '/images_v1/projects/portfolio/the_collector_private_residence/thumbnails/works1.jpg',
      images: [
        '/images_v1/projects/portfolio/the_collector_private_residence/images/001.jpg',
        '/images_v1/projects/portfolio/the_collector_private_residence/images/002.jpg',
        '/images_v1/projects/portfolio/the_collector_private_residence/images/003.jpg',
        '/images_v1/projects/portfolio/the_collector_private_residence/images/004.jpg',
        '/images_v1/projects/portfolio/the_collector_private_residence/images/010 (1).jpg',
        '/images_v1/projects/portfolio/the_collector_private_residence/images/010 (2).jpg',
        '/images_v1/projects/portfolio/the_collector_private_residence/images/021.jpg',
        '/images_v1/projects/portfolio/the_collector_private_residence/images/022.jpg',
        '/images_v1/projects/portfolio/the_collector_private_residence/images/023.jpg',
        '/images_v1/projects/portfolio/the_collector_private_residence/images/025.jpg',
        '/images_v1/projects/portfolio/the_collector_private_residence/images/026.jpg',
        '/images_v1/projects/portfolio/the_collector_private_residence/images/027.jpg',
        '/images_v1/projects/portfolio/the_collector_private_residence/images/030.jpg',
        '/images_v1/projects/portfolio/the_collector_private_residence/images/031.jpg',
   
        '/images_v1/projects/portfolio/the_collector_private_residence/images/040.jpg',
        '/images_v1/projects/portfolio/the_collector_private_residence/images/041.jpg',
        '/images_v1/projects/portfolio/the_collector_private_residence/images/042.jpg',
        '/images_v1/projects/portfolio/the_collector_private_residence/images/043.jpg',
        '/images_v1/projects/portfolio/the_collector_private_residence/images/044.jpg',
        '/images_v1/projects/portfolio/the_collector_private_residence/images/045.jpg',
        '/images_v1/projects/portfolio/the_collector_private_residence/images/050.jpg',
        '/images_v1/projects/portfolio/the_collector_private_residence/images/051.jpg',
        '/images_v1/projects/portfolio/the_collector_private_residence/images/052.jpg',
        '/images_v1/projects/portfolio/the_collector_private_residence/images/053.jpg',
      ],
      client: 'Private',
      slug: 'the-art-collector-private-residence',
      category: 'Portfolio'
    },
    { 
      id: 2, 
      title: 'Al Rawda Reception Villa', 
      type: 'Family Home',
      architects: ['Zaher Bissar'],
      year: 2020,
      location: 'Riyadh',
      description : `This gorgeous 1270 m² project in Riyadh is the family reception villa that makes part of an extensive private complex.
      It is a beautiful example of a luxury contemporary home, infused with Islamic influences that resonate with its vibrant heritage. Original orientalism paintings, crafted antiques, Islamic patterns and intricate noble materials accentuate the identity of the place.`,
      banner:'/images_v1/projects/portfolio/al_rawda_reception_villa/banners/banner4.jpg',
      thumbnail: '/images_v1/projects/portfolio/al_rawda_reception_villa/thumbnails/works2.jpg',
      images: [
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/001.jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/002.jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/003.jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/004.jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/09 (1).jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/09.jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/10 (1).jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/10 (3).jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/15.jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/16.jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/20.jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/21.jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/30.jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/31.jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/32.jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/33.jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/34.jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/35.jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/55 (1).jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/55 (2).jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/55 (3).jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/56.jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/57.jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/58.jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/60.jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/61.jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/62.jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/63.jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/64.jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/65.jpg',
            ],
      client: 'Private',
      slug: 'al-rawda-reception-villa',
      category: 'Portfolio'
    },
    { 
      id: 3, 
      title: 'Al Ghadir Villa', 
      type: 'Family Home',
      architects: ['Zaher Bissar'],
      year: 2019,
      description:'The exclusive interior design of this spacious project that impresses with the elegance and splendor of the timeless furniture pieces is the reception area of this villa. The focal point of this project is a double height space, where a crystal light installation from floor to ceiling is stretching out from floor to ceiling. This piece is called the “Crystal Biosphere”',
      location: 'Riyadh',
      banner:'/images_v1/projects/portfolio/al_ghadir_villa/banners/banner3.jpg',
      thumbnail: '/images_v1/projects/portfolio/al_ghadir_villa/thumbnails/works3.jpg',
      images: [
        '/images_v1/projects/portfolio/al_ghadir_villa/images/001.jpg',
        '/images_v1/projects/portfolio/al_ghadir_villa/images/002.jpg',
        '/images_v1/projects/portfolio/al_ghadir_villa/images/003.jpg',
        '/images_v1/projects/portfolio/al_ghadir_villa/images/004.jpg',
        '/images_v1/projects/portfolio/al_ghadir_villa/images/005.jpg',
        '/images_v1/projects/portfolio/al_ghadir_villa/images/006.jpg',

        '/images_v1/projects/portfolio/al_ghadir_villa/images/010.jpg',
        '/images_v1/projects/portfolio/al_ghadir_villa/images/011.jpg',
        '/images_v1/projects/portfolio/al_ghadir_villa/images/012.jpg',
        '/images_v1/projects/portfolio/al_ghadir_villa/images/013.jpg',
        '/images_v1/projects/portfolio/al_ghadir_villa/images/014.jpg',
        '/images_v1/projects/portfolio/al_ghadir_villa/images/015.jpg',
        '/images_v1/projects/portfolio/al_ghadir_villa/images/016.jpg',
        '/images_v1/projects/portfolio/al_ghadir_villa/images/017.jpg',
        '/images_v1/projects/portfolio/al_ghadir_villa/images/018.jpg',
        '/images_v1/projects/portfolio/al_ghadir_villa/images/020.jpg',
        '/images_v1/projects/portfolio/al_ghadir_villa/images/021.jpg',
        '/images_v1/projects/portfolio/al_ghadir_villa/images/022.jpg',
        '/images_v1/projects/portfolio/al_ghadir_villa/images/023.jpg',
        '/images_v1/projects/portfolio/al_ghadir_villa/images/024.jpg',

        '/images_v1/projects/portfolio/al_ghadir_villa/images/027.jpg',
        '/images_v1/projects/portfolio/al_ghadir_villa/images/alia 16.jpg',
        '/images_v1/projects/portfolio/al_ghadir_villa/images/aRCA (1).jpg',
        '/images_v1/projects/portfolio/al_ghadir_villa/images/aRCA (2).jpg',
        '/images_v1/projects/portfolio/al_ghadir_villa/images/aRCA (3).jpg',
        '/images_v1/projects/portfolio/al_ghadir_villa/images/aRCA (4).jpg',
        '/images_v1/projects/portfolio/al_ghadir_villa/images/aRCA (5).jpg',
      ],
      client: 'Private',
      slug: 'al-ghadir-villa',
      category: 'Portfolio'
    },
    { 
      id: 4, 
      title: 'Al Rawda Private Residence', 
      type: 'Family Home',
      architects: ['Zaher Bissar'],
      year: 2021,
      location: 'Riyadh',
      description: 'This luxury private suite combines exquisite, complex detail work with statement prints and muted walls for a modern Asian inspired aesthetic. Three different wallpapers by “De Gournay” are the catchiest elements in this project. Once again, we went in search of the top furniture brands and unique pieces from different European Galleries. A rich color palette is used throughout, giving a sense of depth to the contemporary space; while accent colors and gold hues add a warm splash of color into the design.',
      banner:'/images_v1/projects/portfolio/al_rawda_private_residence/banners/banner2.jpg',
      thumbnail: '/images_v1/projects/portfolio/al_rawda_private_residence/thumbnails/works4.jpg',
      images: [
        '/images_v1/projects/portfolio/al_rawda_private_residence/images/100.jpg',
        '/images_v1/projects/portfolio/al_rawda_private_residence/images/101.jpg',
        '/images_v1/projects/portfolio/al_rawda_private_residence/images/103.jpg',
        '/images_v1/projects/portfolio/al_rawda_private_residence/images/201.jpg',
        '/images_v1/projects/portfolio/al_rawda_private_residence/images/202.jpg',
        '/images_v1/projects/portfolio/al_rawda_private_residence/images/204.jpg',
        '/images_v1/projects/portfolio/al_rawda_private_residence/images/205.jpg',
        '/images_v1/projects/portfolio/al_rawda_private_residence/images/300.jpg',
        '/images_v1/projects/portfolio/al_rawda_private_residence/images/301.jpg',
        '/images_v1/projects/portfolio/al_rawda_private_residence/images/302.jpg',
        '/images_v1/projects/portfolio/al_rawda_private_residence/images/303.jpg',
        '/images_v1/projects/portfolio/al_rawda_private_residence/images/304.jpg',
        '/images_v1/projects/portfolio/al_rawda_private_residence/images/401.jpg',
        '/images_v1/projects/portfolio/al_rawda_private_residence/images/403.jpg',
        '/images_v1/projects/portfolio/al_rawda_private_residence/images/Asian (3).jpg',
        '/images_v1/projects/portfolio/al_rawda_private_residence/images/Asian (4).jpg',
      ],
      client: 'Private',
      slug: 'al-rawda-private-residence',
      category: 'Portfolio'
    },
    { 
      id: 5, 
      title: 'The Sisters Villa', 
      type: 'Family Home',
      architects: ['Zaher Bissar'],
      year: 2018,
      location: 'Riyadh',
      description:"From the first meeting the three sisters had a clear vision in mind: a stylish place that challenges the norms of residential design. The handsome style is a perfect blend of Luxury Contemporary and Urban Chic where plain walls and smart fabrics set the mood of the space. They are all tied together with one-of-a- kind furniture pieces and statement artworks. The ensemble aligns perfectly with the homeowner’s vision, taste and lifestyle. Have a look!",
      banner:'/images_v1/projects/portfolio/the_sisters_villa/banners/banner5.jpg',
      thumbnail: '/images_v1/projects/portfolio/the_sisters_villa/thumbnails/works5.jpg',
      images: [
        '/images_v1/projects/portfolio/the_sisters_villa/images/01.jpg', 
        '/images_v1/projects/portfolio/the_sisters_villa/images/02.jpg', 
        '/images_v1/projects/portfolio/the_sisters_villa/images/03.jpg',
        '/images_v1/projects/portfolio/the_sisters_villa/images/04.jpg',              
        '/images_v1/projects/portfolio/the_sisters_villa/images/05.jpg',              
        '/images_v1/projects/portfolio/the_sisters_villa/images/06.jpg',              
        '/images_v1/projects/portfolio/the_sisters_villa/images/07.jpg', 
        '/images_v1/projects/portfolio/the_sisters_villa/images/200.jpg', 
        '/images_v1/projects/portfolio/the_sisters_villa/images/201.jpg', 
        '/images_v1/projects/portfolio/the_sisters_villa/images/211.jpg', 
        '/images_v1/projects/portfolio/the_sisters_villa/images/212.jpg', 
        '/images_v1/projects/portfolio/the_sisters_villa/images/213.jpg', 
        '/images_v1/projects/portfolio/the_sisters_villa/images/215.jpg', 
        '/images_v1/projects/portfolio/the_sisters_villa/images/220.jpg', 
        '/images_v1/projects/portfolio/the_sisters_villa/images/221.jpg', 
        '/images_v1/projects/portfolio/the_sisters_villa/images/225.jpg', 
        '/images_v1/projects/portfolio/the_sisters_villa/images/230.jpg', 
        '/images_v1/projects/portfolio/the_sisters_villa/images/235.jpg', 
      ],
      client: 'Private',
      slug: 'the-sisters-villa',
      category: 'Portfolio'
    },
    { 
      id: 6, 
      title: 'Jenadriah Ranch', 
      type: 'Pool House',
      architects: ['Zaher Bissar'],
      year: 2022,
      location: 'Riyadh',
      description:'Layered Textures, earthy tones, hints of sleek patterns and crochet accents with a bold natural wood are just what you need for achieving a Boho-Chic look. The focal point is a wooden backdrop versus expansive glass walls overlooking the pool and its green surrounding. This pool house is a free-standing building in the middle of an extensive green area; This ranch is located in Jenadriah, a suburb of Riyadh city.',
      banner:'/images_v1/projects/portfolio/jenadriah_ranch/banners/banner6.jpg',
      thumbnail: '/images_v1/projects/portfolio/jenadriah_ranch/thumbnails/works6.jpg',
      images: [
        '/images_v1/projects/portfolio/jenadriah_ranch/images/000.jpg',
        '/images_v1/projects/portfolio/jenadriah_ranch/images/001.jpg',
        '/images_v1/projects/portfolio/jenadriah_ranch/images/002.jpg',
        '/images_v1/projects/portfolio/jenadriah_ranch/images/03.jpg',
        '/images_v1/projects/portfolio/jenadriah_ranch/images/04.jpg',              
        '/images_v1/projects/portfolio/jenadriah_ranch/images/05.jpg',              
        '/images_v1/projects/portfolio/jenadriah_ranch/images/06.jpg',              
        '/images_v1/projects/portfolio/jenadriah_ranch/images/07.jpg',              
        '/images_v1/projects/portfolio/jenadriah_ranch/images/08.jpg',              
        '/images_v1/projects/portfolio/jenadriah_ranch/images/09.jpg',              
        '/images_v1/projects/portfolio/jenadriah_ranch/images/10.jpg',              
      ],
      client: 'Private',
      slug: 'jenadriah_ranch',
      category: 'Portfolio'
    },
    // { 
    //   id: 7, 
    //   title: 'Modern Loft', 
    //   type: 'Living',
    //   completion_date: '2021-04-20',
    //   architects: ['Zaher Bissar'],
    //   year: 2021,
    //   location: 'Seattle, WA',
    //   description : `Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore.`,
    //   banner:'/images/innerhero/projectdetails.webp',
    //   thumbnail: '/images_v1/projects/portfolio/thumbnails/works1.jpg',
    //   images: [
    //     '/images_v1/projects/portfolio/images/image.webp',
    //     '/images_v1/projects/portfolio/images/image.webp',
    //     '/images_v1/projects/portfolio/images/image.webp',
    //     '/images_v1/projects/portfolio/images/image.webp',
    //     '/images_v1/projects/portfolio/images/image.webp',
    //     '/images_v1/projects/portfolio/images/image.webp',
    //     '/images_v1/projects/portfolio/images/image.webp'
    //   ],
    //   client: 'Loft Living Co.',
    //   slug: 'modern-loft',
    //   category: 'Portfolio'
    // },
    // { 
    //   id: 8, 
    //   title: 'Seaside Retreat', 
    //   type: 'Houses',
    //   completion_date: '2022-07-12',
    //   architects: ['Zaher Bissar'],
    //   year: 2022,
    //   location: 'Dubai, UAE',
    //   description : `Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore.`,
    //   banner:'/images/innerhero/projectdetails.webp',
    //   thumbnail: '/images_v1/projects/portfolio/thumbnails/works2.jpg',
    //   images: [
    //     '/images_v1/projects/portfolio/images/image.webp',
    //     '/images_v1/projects/portfolio/images/image.webp',
    //     '/images_v1/projects/portfolio/images/image.webp',
    //     '/images_v1/projects/portfolio/images/image.webp',
    //     '/images_v1/projects/portfolio/images/image.webp',
    //     '/images_v1/projects/portfolio/images/image.webp',
    //     '/images_v1/projects/portfolio/images/image.webp',
    //     '/images_v1/projects/portfolio/images/image.webp'
    //   ],
    //   client: 'Beachside Estates',
    //   slug: 'seaside-retreat',
    //   category: 'Portfolio'
    // },
    // { 
    //   id: 9, 
    //   title: 'Penthouse Suite', 
    //   type: 'Houses',
    //   completion_date: '2023-01-10',
    //   architects: ['Zaher Bissar'],
    //   year: 2023,
    //   location: 'Dubai, UAE',
    //   description : `Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore.`,
    //   banner:'/images/innerhero/projectdetails.webp',
    //   thumbnail: '/images_v1/projects/portfolio/thumbnails/works3.jpg',
    //   images: [
    //     '/images_v1/projects/portfolio/images/image.webp',
    //     '/images_v1/projects/portfolio/images/image.webp',
    //     '/images_v1/projects/portfolio/images/image.webp',
    //     '/images_v1/projects/portfolio/images/image.webp',
    //     '/images_v1/projects/portfolio/images/image.webp',
    //     '/images_v1/projects/portfolio/images/image.webp',
    //     '/images_v1/projects/portfolio/images/image.webp',
    //     '/images_v1/projects/portfolio/images/image.webp',
    //     '/images_v1/projects/portfolio/images/image.webp'
    //   ],
    //   client: 'Luxury Living Group',
    //   slug: 'penthouse-suite',
    //   category: 'Portfolio'
    // }
  ];
}

export function getPortfolioProjectBySlug(slug) {
  let projects = getProtfolioProjects();
  return projects.find(project => project.slug === slug);
}

export function getCollabsProjects() {
  return [
    { 
      id: 1, 
      title: 'De Gournay', 
      type: 'Design',
      year: 2020,
      location: 'Riyadh',
      banner:'/images_v1/projects/collaborations/de_gournay/banners/banner1.jpg',
      thumbnail: '/images_v1/projects/collaborations/de_gournay/thumbnails/collabs1.jpg',
      images: [
        '/images_v1/projects/collaborations/de_gournay/images/DG1 (1).jpg',
        '/images_v1/projects/collaborations/de_gournay/images/DG1 (3).jpg',
        '/images_v1/projects/collaborations/de_gournay/images/DG1 (3a).jpg',
        '/images_v1/projects/collaborations/de_gournay/images/DG1 (4).jpg',
        '/images_v1/projects/collaborations/de_gournay/images/DG1 (5).jpg',
        '/images_v1/projects/collaborations/de_gournay/images/DG1 (6).jpg',
        '/images_v1/projects/collaborations/de_gournay/images/DG1 (7).jpg',
        '/images_v1/projects/collaborations/de_gournay/images/DG2 (1).jpg',
        '/images_v1/projects/collaborations/de_gournay/images/DG2 (2).jpg',
        '/images_v1/projects/collaborations/de_gournay/images/DG2 (3).jpg',
      ],
      slug: 'de-gournay',
      category: 'Collaborations'
    },
    { 
      id: 2, 
      title: 'Preciosa', 
      type: 'Interior',
      year: 2022,
      location: 'Riyadh',
      banner:'/images_v1/projects/collaborations/preciosa/banners/banner3.jpg',
      thumbnail: '/images_v1/projects/collaborations/preciosa/thumbnails/collabs3.jpg',
      images: [
        '/images_v1/projects/collaborations/preciosa/images/PR1 (1).jpg',
        '/images_v1/projects/collaborations/preciosa/images/PR1 (5).jpg',
        '/images_v1/projects/collaborations/preciosa/images/PR1 (6).jpg',
        '/images_v1/projects/collaborations/preciosa/images/PR1 (7).jpg',
        '/images_v1/projects/collaborations/preciosa/images/PR2.jpg',
        '/images_v1/projects/collaborations/preciosa/images/PR10.jpg',
        '/images_v1/projects/collaborations/preciosa/images/PR20 (1).jpg',
        '/images_v1/projects/collaborations/preciosa/images/PR20 (2).jpg',
        '/images_v1/projects/collaborations/preciosa/images/PR30.jpg',
        '/images_v1/projects/collaborations/preciosa/images/PR31.jpg',

      ],
      slug: 'preciosa',
      category: 'Collaborations'
    },    
    { 
      id: 3, 
      title: 'Baccarat', 
      type: 'Houses',
      year: 2019,
      location: 'Riyadh',
      banner:'/images_v1/projects/collaborations/baccarat/banners/banner2.jpg',
      thumbnail: '/images_v1/projects/collaborations/baccarat/thumbnails/collabs2.jpg',
      images: [
        '/images_v1/projects/collaborations/baccarat/images/001.jpg',
        '/images_v1/projects/collaborations/baccarat/images/1 Swipe 1.jpg',
        '/images_v1/projects/collaborations/baccarat/images/2 Swipe 2.jpg',
        '/images_v1/projects/collaborations/baccarat/images/002.jpg',
        '/images_v1/projects/collaborations/baccarat/images/003.jpg',
        '/images_v1/projects/collaborations/baccarat/images/012.jpg',
        '/images_v1/projects/collaborations/baccarat/images/IMG_9540.jpg',
        '/images_v1/projects/collaborations/baccarat/images/IMG_9542.jpg',
        '/images_v1/projects/collaborations/baccarat/images/IMG_9543.jpg',
        '/images_v1/projects/collaborations/baccarat/images/Optional.jpg',

      ],
      slug: 'baccarat',
      category: 'Collaborations'
    },
    { 
      id: 4, 
      title: 'Italamp', 
      type: 'Living',
      year: 2022,
      location: 'Riyadh',
      banner:'/images_v1/projects/collaborations/italamp/banners/banner4.jpg',
      thumbnail: '/images_v1/projects/collaborations/italamp/thumbnails/collabs4.jpg',
      images: [
        '/images_v1/projects/collaborations/italamp/images/023 Corridor (18).jpg',
        '/images_v1/projects/collaborations/italamp/images/023 Corridor (19).jpg',
        '/images_v1/projects/collaborations/italamp/images/023 Corridor (31).jpg',
        '/images_v1/projects/collaborations/italamp/images/IMG_6656.jpg',
        '/images_v1/projects/collaborations/italamp/images/IMG_6665.jpg',
      ],
      slug: 'italamp',
      category: 'Collaborations'
    },
    // { 
    //   id: 5, 
    //   title: 'Eco-Friendly Office Space', 
    //   type: 'Design',
    //   completion_date: '2019-10-05',
    //   architects: ['Zaher Bissar', 'Laura White'],
    //   year: 2019,
    //   location: 'Berlin, Germany',
    //   description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`,
    //    banner:'/images/innerhero/projectdetails.webp',
    //   thumbnail: '/images_v1/projects/collaborations/thumbnails/collabs1.jpg',
    //   images: [
    //     '/images_v1/projects/collaborations/images/image.webp',
    //     '/images_v1/projects/collaborations/images/image.webp',
    //     '/images_v1/projects/collaborations/images/image.webp',
    //     '/images_v1/projects/collaborations/images/image.webp',
    //     '/images_v1/projects/collaborations/images/image.webp',
    //     '/images_v1/projects/collaborations/images/image.webp',
    //     '/images_v1/projects/collaborations/images/image.webp',
    //   ],
    //   client: 'Green Innovators',
    //   slug: 'eco-friendly-office-space',
    //   category: 'Collaborations'
    // },
    // { 
    //   id: 6, 
    //   title: 'Modern Residential Tower', 
    //   type: 'Houses',
    //   completion_date: '2018-04-12',
    //   architects: ['Zaher Bissar', 'David Black', 'Sophia Green'],
    //   year: 2018,
    //   location: 'Tokyo, Japan',
    //   description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`,
    //    banner:'/images/innerhero/projectdetails.webp',
    //   thumbnail: '/images_v1/projects/collaborations/thumbnails/collabs2.jpg',
    //   images: [
    //     '/images_v1/projects/collaborations/images/image.webp',
    //     '/images_v1/projects/collaborations/images/image.webp',
    //     '/images_v1/projects/collaborations/images/image.webp',
    //     '/images_v1/projects/collaborations/images/image.webp',
    //     '/images_v1/projects/collaborations/images/image.webp',
    //     '/images_v1/projects/collaborations/images/image.webp',
    //     '/images_v1/projects/collaborations/images/image.webp',
    //   ],
    //   client: 'Tokyo Builders Inc.',
    //   slug: 'modern-residential-tower',
    //   category: 'Collaborations'
    // }
  ];
}

export function getCollabsProjectBySlug(slug) {
  let projects = getCollabsProjects();
  return projects.find(project => project.slug === slug);
}

export function getEditorial() {
  return [
    { 
      title: 'Editorial Art Gallery', 
      image:'/images_v1/editorial/images/03.jpg',
    },     
        { 
      title: 'Editorial Art Gallery', 
      image:'/images_v1/editorial/images/01 Main Photo.jpg',
    },         
    { 
      title: 'Editorial Art Gallery', 
      image:'/images_v1/editorial/images/01_Resized.jpg',
    },
    { 
      title: 'Editorial Art Gallery', 
      image:'/images_v1/editorial/images/02_Resized.jpg',
    },    
    { 
      title: 'Editorial Art Gallery', 
      image:'/images_v1/editorial/images/03_Resized.jpg',
    },    
    // { 
    //   title: 'Editorial Art Gallery', 
    //   image:'/images/editorial/images/Rectangle 03_Resized.webp',
    // },  

    { 
      title: 'Editorial Art Gallery', 
      image:'/images_v1/editorial/images/04_Resized.jpg',
    },      
    { 
      title: 'Editorial Art Gallery', 
      image:'/images_v1/editorial/images/05_Resized.jpg',
    },     
    { 
      title: 'Editorial Art Gallery', 
      image:'/images_v1/editorial/images/06_Resized.jpg',
    }, 
    { 
      title: 'Editorial Art Gallery', 
      image:'/images_v1/editorial/images/07_Resized.jpg',
    },     
    { 
      id: 10, 
      title: 'Editorial Art Gallery', 
      image:'/images_v1/editorial/images/08_Resized.jpg',
    },    
    { 
      title: 'Editorial Art Gallery', 
      image:'/images_v1/editorial/images/09_Resized.jpg',
    },   
    { 
      title: 'Editorial Art Gallery', 
      image:'/images_v1/editorial/images/10_Resized.jpg',
    },     
    { 
      title: 'Editorial Art Gallery', 
      image:'/images_v1/editorial/images/12_Resized.jpg',
    },     
    { 
      title: 'Editorial Art Gallery', 
      image:'/images_v1/editorial/images/13_Resized.jpg',
    },
    { 
      title: 'Editorial Art Gallery', 
      image:'/images_v1/editorial/images/14_Resized.jpg',
    },
    { 
      title: 'Editorial Art Gallery', 
      image:'/images_v1/editorial/images/15_Resized.jpg',
    },    
    { 
      title: 'Editorial Art Gallery', 
      image:'/images_v1/editorial/images/16_Resized.jpg',
    },
  ]
}

export function getAccordion() {
  return [
    { 
      id: 1, 
      title: 'The creative mind', 
      content: 'Armed with boundless creativity and an unwavering passion for interior design, Zaher Bissar embarked on a journey back in 2014, founding Bissar Concepts. His commitment to crafting spaces that echo an artistic vision and a relentless pursuit of beauty has captivated clients and admirers alike. Bissar Concept’s portfolio grew, each project bearing the imprint of its unique design. With time, what began as a solitary venture evolved into a thriving interior design company, reflecting the intricate charm of interior design.'
    },
    { 
      id: 2, 
      title: 'Our Story', 
      content: 'Currently situated in Riyadh, with a strong presence in Beirut, Bissar Concepts is the epitome of sophisticated living. Having extended its influence across the region, the luxury atelier holds hundreds of projects spanning across KSA, UAE, the Levant, and Egypt. Bissar Concepts offers a world of bespoke luxury, ranging from intricate architectural refinement to customized design, where every space is meticulously curated to illustrate elegance and refinement. Our studio fully integrates interior design services specialized in upscale projects including palaces, private residences, public buildings, corporate offices, and hotels.'
    },    
    { 
      id: 3, 
      title: 'Our Approach', 
      content: 'By taking a fresh approach to design, we create viable and dynamic spaces that are as unique as the individuality of each of our clients. Our work ranges from minimalism to classicism, with luxury contemporary defining most of our projects. We aim to consistently reflect the timeless elegance of classical aesthetics, but also introduce tradition with a modern flair.'
    },    
    { 
      id: 4, 
      title: 'Our Philosophy', 
      content: 'Authenticity, individuality, and innovation are the cornerstone of every project we undertake. Our work is designed to blend aesthetics with functionality, seamlessly integrating the aspirations and lifestyles of our clients into every detail with finesse and a focus on well-being. Drawing inspiration from light, nature, and the art of equilibrium, our interior architecture serves as the foundation of our conceptual framework. Meanwhile, the essence of our philosophy is defined by the use of noble materials, luxurious detailing, and refined design. Our mission transcends the ordinary, aiming to orchestrate immersive experiences that captivate the senses: mentally by adding elements of surprise, spiritually by stimulating tranquillity, and culturally by infusing art and history.'
    }
  ]
}
export function getAllProjects() {
  return [
    { 
      id: 1, 
      title: 'The Art Collector Private Residence', 
      type: 'Private Residence',
      architects: ['Zaher Bissar'],
      year: 2022,
      location: 'Riyadh',
      description : `One of the first assignments for us is to set the inspiration for the project; we invest a tremendous amount of time seeking inspiration from our client’s lifestyle and personal tastes. Aware of our client’s interest in fine art, we have selected masterpieces from the most prestigious galleries in the world. The warm and textured wooden high walls has created the perfect background for these art pieces.
      This project with fortunate high ceilings was transformed into a hidden museum in a private home.`,      
      banner:'/images_v1/projects/portfolio/the_collector_private_residence/banners/banner1.jpg',
      thumbnail: '/images_v1/projects/portfolio/the_collector_private_residence/thumbnails/works1.jpg',
      images: [
        '/images_v1/projects/portfolio/the_collector_private_residence/images/001.jpg',
        '/images_v1/projects/portfolio/the_collector_private_residence/images/002.jpg',
        '/images_v1/projects/portfolio/the_collector_private_residence/images/003.jpg',
        '/images_v1/projects/portfolio/the_collector_private_residence/images/004.jpg',
        '/images_v1/projects/portfolio/the_collector_private_residence/images/010 (1).jpg',
        '/images_v1/projects/portfolio/the_collector_private_residence/images/010 (2).jpg',
        '/images_v1/projects/portfolio/the_collector_private_residence/images/021.jpg',
        '/images_v1/projects/portfolio/the_collector_private_residence/images/022.jpg',
        '/images_v1/projects/portfolio/the_collector_private_residence/images/023.jpg',
        '/images_v1/projects/portfolio/the_collector_private_residence/images/025.jpg',
        '/images_v1/projects/portfolio/the_collector_private_residence/images/026.jpg',
        '/images_v1/projects/portfolio/the_collector_private_residence/images/027.jpg',
        '/images_v1/projects/portfolio/the_collector_private_residence/images/030.jpg',
        '/images_v1/projects/portfolio/the_collector_private_residence/images/031.jpg',
   
        '/images_v1/projects/portfolio/the_collector_private_residence/images/040.jpg',
        '/images_v1/projects/portfolio/the_collector_private_residence/images/041.jpg',
        '/images_v1/projects/portfolio/the_collector_private_residence/images/042.jpg',
        '/images_v1/projects/portfolio/the_collector_private_residence/images/043.jpg',
        '/images_v1/projects/portfolio/the_collector_private_residence/images/044.jpg',
        '/images_v1/projects/portfolio/the_collector_private_residence/images/045.jpg',
        '/images_v1/projects/portfolio/the_collector_private_residence/images/050.jpg',
        '/images_v1/projects/portfolio/the_collector_private_residence/images/051.jpg',
        '/images_v1/projects/portfolio/the_collector_private_residence/images/052.jpg',
        '/images_v1/projects/portfolio/the_collector_private_residence/images/053.jpg',
      ],
      client: 'Private',
      slug: 'the-art-collector-private-residence',
      category: 'Portfolio'
    },
    { 
      id: 2, 
      title: 'Al Rawda Reception Villa', 
      type: 'Family Home',
      architects: ['Zaher Bissar'],
      year: 2020,
      location: 'Riyadh',
      description : `This gorgeous 1270 m² project in Riyadh is the family reception villa that makes part of an extensive private complex.
      It is a beautiful example of a luxury contemporary home, infused with Islamic influences that resonate with its vibrant heritage. Original orientalism paintings, crafted antiques, Islamic patterns and intricate noble materials accentuate the identity of the place.`,
      banner:'/images_v1/projects/portfolio/al_rawda_reception_villa/banners/banner4.jpg',
      thumbnail: '/images_v1/projects/portfolio/al_rawda_reception_villa/thumbnails/works2.jpg',
      images: [
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/001.jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/002.jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/003.jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/004.jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/09 (1).jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/09.jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/10 (1).jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/10 (3).jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/15.jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/16.jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/20.jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/21.jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/30.jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/31.jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/32.jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/33.jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/34.jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/35.jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/55 (1).jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/55 (2).jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/55 (3).jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/56.jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/57.jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/58.jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/60.jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/61.jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/62.jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/63.jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/64.jpg',
        '/images_v1/projects/portfolio/al_rawda_reception_villa/images/65.jpg',
            ],
      client: 'Private',
      slug: 'al-rawda-reception-villa',
      category: 'Portfolio'
    },
    { 
      id: 3, 
      title: 'Al Ghadir Villa', 
      type: 'Family Home',
      architects: ['Zaher Bissar'],
      year: 2019,
      description:'The exclusive interior design of this spacious project that impresses with the elegance and splendor of the timeless furniture pieces is the reception area of this villa. The focal point of this project is a double height space, where a crystal light installation from floor to ceiling is stretching out from floor to ceiling. This piece is called the “Crystal Biosphere”',
      location: 'Riyadh',
      banner:'/images_v1/projects/portfolio/al_ghadir_villa/banners/banner3.jpg',
      thumbnail: '/images_v1/projects/portfolio/al_ghadir_villa/thumbnails/works3.jpg',
      images: [
        '/images_v1/projects/portfolio/al_ghadir_villa/images/001.jpg',
        '/images_v1/projects/portfolio/al_ghadir_villa/images/002.jpg',
        '/images_v1/projects/portfolio/al_ghadir_villa/images/003.jpg',
        '/images_v1/projects/portfolio/al_ghadir_villa/images/004.jpg',
        '/images_v1/projects/portfolio/al_ghadir_villa/images/005.jpg',
        '/images_v1/projects/portfolio/al_ghadir_villa/images/006.jpg',

        '/images_v1/projects/portfolio/al_ghadir_villa/images/010.jpg',
        '/images_v1/projects/portfolio/al_ghadir_villa/images/011.jpg',
        '/images_v1/projects/portfolio/al_ghadir_villa/images/012.jpg',
        '/images_v1/projects/portfolio/al_ghadir_villa/images/013.jpg',
        '/images_v1/projects/portfolio/al_ghadir_villa/images/014.jpg',
        '/images_v1/projects/portfolio/al_ghadir_villa/images/015.jpg',
        '/images_v1/projects/portfolio/al_ghadir_villa/images/016.jpg',
        '/images_v1/projects/portfolio/al_ghadir_villa/images/017.jpg',
        '/images_v1/projects/portfolio/al_ghadir_villa/images/018.jpg',
        '/images_v1/projects/portfolio/al_ghadir_villa/images/020.jpg',
        '/images_v1/projects/portfolio/al_ghadir_villa/images/021.jpg',
        '/images_v1/projects/portfolio/al_ghadir_villa/images/022.jpg',
        '/images_v1/projects/portfolio/al_ghadir_villa/images/023.jpg',
        '/images_v1/projects/portfolio/al_ghadir_villa/images/024.jpg',

        '/images_v1/projects/portfolio/al_ghadir_villa/images/027.jpg',
        '/images_v1/projects/portfolio/al_ghadir_villa/images/alia 16.jpg',
        '/images_v1/projects/portfolio/al_ghadir_villa/images/aRCA (1).jpg',
        '/images_v1/projects/portfolio/al_ghadir_villa/images/aRCA (2).jpg',
        '/images_v1/projects/portfolio/al_ghadir_villa/images/aRCA (3).jpg',
        '/images_v1/projects/portfolio/al_ghadir_villa/images/aRCA (4).jpg',
        '/images_v1/projects/portfolio/al_ghadir_villa/images/aRCA (5).jpg',
      ],
      client: 'Private',
      slug: 'al-ghadir-villa',
      category: 'Portfolio'
    },
    { 
      id: 4, 
      title: 'Al Rawda Private Residence', 
      type: 'Family Home',
      architects: ['Zaher Bissar'],
      year: 2021,
      location: 'Riyadh',
      description: 'This luxury private suite combines exquisite, complex detail work with statement prints and muted walls for a modern Asian inspired aesthetic. Three different wallpapers by “De Gournay” are the catchiest elements in this project. Once again, we went in search of the top furniture brands and unique pieces from different European Galleries. A rich color palette is used throughout, giving a sense of depth to the contemporary space; while accent colors and gold hues add a warm splash of color into the design.',
      banner:'/images_v1/projects/portfolio/al_rawda_private_residence/banners/banner2.jpg',
      thumbnail: '/images_v1/projects/portfolio/al_rawda_private_residence/thumbnails/works4.jpg',
      images: [
        '/images_v1/projects/portfolio/al_rawda_private_residence/images/100.jpg',
        '/images_v1/projects/portfolio/al_rawda_private_residence/images/101.jpg',
        '/images_v1/projects/portfolio/al_rawda_private_residence/images/103.jpg',
        '/images_v1/projects/portfolio/al_rawda_private_residence/images/201.jpg',
        '/images_v1/projects/portfolio/al_rawda_private_residence/images/202.jpg',
        '/images_v1/projects/portfolio/al_rawda_private_residence/images/204.jpg',
        '/images_v1/projects/portfolio/al_rawda_private_residence/images/205.jpg',
        '/images_v1/projects/portfolio/al_rawda_private_residence/images/300.jpg',
        '/images_v1/projects/portfolio/al_rawda_private_residence/images/301.jpg',
        '/images_v1/projects/portfolio/al_rawda_private_residence/images/302.jpg',
        '/images_v1/projects/portfolio/al_rawda_private_residence/images/303.jpg',
        '/images_v1/projects/portfolio/al_rawda_private_residence/images/304.jpg',
        '/images_v1/projects/portfolio/al_rawda_private_residence/images/401.jpg',
        '/images_v1/projects/portfolio/al_rawda_private_residence/images/403.jpg',
        '/images_v1/projects/portfolio/al_rawda_private_residence/images/Asian (3).jpg',
        '/images_v1/projects/portfolio/al_rawda_private_residence/images/Asian (4).jpg',
      ],
      client: 'Private',
      slug: 'al-rawda-private-residence',
      category: 'Portfolio'
    },
    { 
      id: 5, 
      title: 'The Sisters Villa', 
      type: 'Family Home',
      architects: ['Zaher Bissar'],
      year: 2018,
      location: 'Riyadh',
      description:"From the first meeting the three sisters had a clear vision in mind: a stylish place that challenges the norms of residential design. The handsome style is a perfect blend of Luxury Contemporary and Urban Chic where plain walls and smart fabrics set the mood of the space. They are all tied together with one-of-a- kind furniture pieces and statement artworks. The ensemble aligns perfectly with the homeowner’s vision, taste and lifestyle. Have a look!",
      banner:'/images_v1/projects/portfolio/the_sisters_villa/banners/banner5.jpg',
      thumbnail: '/images_v1/projects/portfolio/the_sisters_villa/thumbnails/works5.jpg',
      images: [
        '/images_v1/projects/portfolio/the_sisters_villa/images/01.jpg', 
        '/images_v1/projects/portfolio/the_sisters_villa/images/02.jpg', 
        '/images_v1/projects/portfolio/the_sisters_villa/images/03.jpg',
        '/images_v1/projects/portfolio/the_sisters_villa/images/04.jpg',              
        '/images_v1/projects/portfolio/the_sisters_villa/images/05.jpg',              
        '/images_v1/projects/portfolio/the_sisters_villa/images/06.jpg',              
        '/images_v1/projects/portfolio/the_sisters_villa/images/07.jpg', 
        '/images_v1/projects/portfolio/the_sisters_villa/images/200.jpg', 
        '/images_v1/projects/portfolio/the_sisters_villa/images/201.jpg', 
        '/images_v1/projects/portfolio/the_sisters_villa/images/211.jpg', 
        '/images_v1/projects/portfolio/the_sisters_villa/images/212.jpg', 
        '/images_v1/projects/portfolio/the_sisters_villa/images/213.jpg', 
        '/images_v1/projects/portfolio/the_sisters_villa/images/215.jpg', 
        '/images_v1/projects/portfolio/the_sisters_villa/images/220.jpg', 
        '/images_v1/projects/portfolio/the_sisters_villa/images/221.jpg', 
        '/images_v1/projects/portfolio/the_sisters_villa/images/225.jpg', 
        '/images_v1/projects/portfolio/the_sisters_villa/images/230.jpg', 
        '/images_v1/projects/portfolio/the_sisters_villa/images/235.jpg', 
      ],
      client: 'Private',
      slug: 'the-sisters-villa',
      category: 'Portfolio'
    },
    { 
      id: 6, 
      title: 'Jenadriah Ranch', 
      type: 'Pool House',
      architects: ['Zaher Bissar'],
      year: 2022,
      location: 'Riyadh',
      description:'Layered Textures, earthy tones, hints of sleek patterns and crochet accents with a bold natural wood are just what you need for achieving a Boho-Chic look. The focal point is a wooden backdrop versus expansive glass walls overlooking the pool and its green surrounding. This pool house is a free-standing building in the middle of an extensive green area; This ranch is located in Jenadriah, a suburb of Riyadh city.',
      banner:'/images_v1/projects/portfolio/jenadriah_ranch/banners/banner6.jpg',
      thumbnail: '/images_v1/projects/portfolio/jenadriah_ranch/thumbnails/works6.jpg',
      images: [
        '/images_v1/projects/portfolio/jenadriah_ranch/images/000.jpg',
        '/images_v1/projects/portfolio/jenadriah_ranch/images/001.jpg',
        '/images_v1/projects/portfolio/jenadriah_ranch/images/002.jpg',
        '/images_v1/projects/portfolio/jenadriah_ranch/images/03.jpg',
        '/images_v1/projects/portfolio/jenadriah_ranch/images/04.jpg',              
        '/images_v1/projects/portfolio/jenadriah_ranch/images/05.jpg',              
        '/images_v1/projects/portfolio/jenadriah_ranch/images/06.jpg',              
        '/images_v1/projects/portfolio/jenadriah_ranch/images/07.jpg',              
        '/images_v1/projects/portfolio/jenadriah_ranch/images/08.jpg',              
        '/images_v1/projects/portfolio/jenadriah_ranch/images/09.jpg',              
        '/images_v1/projects/portfolio/jenadriah_ranch/images/10.jpg',              
      ],
      client: 'Private',
      slug: 'jenadriah_ranch',
      category: 'Portfolio'
    },
    { 
      id: 7, 
      title: 'De Gournay', 
      type: 'Design',
      year: 2020,
      location: 'Riyadh',
      banner:'/images_v1/projects/collaborations/de_gournay/banners/banner1.jpg',
      thumbnail: '/images_v1/projects/collaborations/de_gournay/thumbnails/collabs1.jpg',
      images: [
        '/images_v1/projects/collaborations/de_gournay/images/DG1 (1).jpg',
        '/images_v1/projects/collaborations/de_gournay/images/DG1 (3).jpg',
        '/images_v1/projects/collaborations/de_gournay/images/DG1 (3a).jpg',
        '/images_v1/projects/collaborations/de_gournay/images/DG1 (4).jpg',
        '/images_v1/projects/collaborations/de_gournay/images/DG1 (5).jpg',
        '/images_v1/projects/collaborations/de_gournay/images/DG1 (6).jpg',
        '/images_v1/projects/collaborations/de_gournay/images/DG1 (7).jpg',
        '/images_v1/projects/collaborations/de_gournay/images/DG2 (1).jpg',
        '/images_v1/projects/collaborations/de_gournay/images/DG2 (2).jpg',
        '/images_v1/projects/collaborations/de_gournay/images/DG2 (3).jpg',
      ],
      slug: 'de-gournay',
      category: 'Collaborations'
    },
    { 
      id: 8, 
      title: 'Preciosa', 
      type: 'Interior',
      year: 2022,
      location: 'Riyadh',
      banner:'/images_v1/projects/collaborations/preciosa/banners/banner3.jpg',
      thumbnail: '/images_v1/projects/collaborations/preciosa/thumbnails/collabs3.jpg',
      images: [
        '/images_v1/projects/collaborations/preciosa/images/PR1 (1).jpg',
        '/images_v1/projects/collaborations/preciosa/images/PR1 (5).jpg',
        '/images_v1/projects/collaborations/preciosa/images/PR1 (6).jpg',
        '/images_v1/projects/collaborations/preciosa/images/PR1 (7).jpg',
        '/images_v1/projects/collaborations/preciosa/images/PR2.jpg',
        '/images_v1/projects/collaborations/preciosa/images/PR10.jpg',
        '/images_v1/projects/collaborations/preciosa/images/PR20 (1).jpg',
        '/images_v1/projects/collaborations/preciosa/images/PR20 (2).jpg',
        '/images_v1/projects/collaborations/preciosa/images/PR30.jpg',
        '/images_v1/projects/collaborations/preciosa/images/PR31.jpg',

      ],
      slug: 'preciosa',
      category: 'Collaborations'
    },    
    { 
      id: 9, 
      title: 'Baccarat', 
      type: 'Houses',
      year: 2019,
      location: 'Riyadh',
      banner:'/images_v1/projects/collaborations/baccarat/banners/banner2.jpg',
      thumbnail: '/images_v1/projects/collaborations/baccarat/thumbnails/collabs2.jpg',
      images: [
        '/images_v1/projects/collaborations/baccarat/images/001.jpg',
        '/images_v1/projects/collaborations/baccarat/images/1 Swipe 1.jpg',
        '/images_v1/projects/collaborations/baccarat/images/2 Swipe 2.jpg',
        '/images_v1/projects/collaborations/baccarat/images/002.jpg',
        '/images_v1/projects/collaborations/baccarat/images/003.jpg',
        '/images_v1/projects/collaborations/baccarat/images/012.jpg',
        '/images_v1/projects/collaborations/baccarat/images/IMG_9540.jpg',
        '/images_v1/projects/collaborations/baccarat/images/IMG_9542.jpg',
        '/images_v1/projects/collaborations/baccarat/images/IMG_9543.jpg',
        '/images_v1/projects/collaborations/baccarat/images/Optional.jpg',

      ],
      slug: 'baccarat',
      category: 'Collaborations'
    },
    { 
      id: 10, 
      title: 'Italamp', 
      type: 'Living',
      year: 2022,
      location: 'Riyadh',
      banner:'/images_v1/projects/collaborations/italamp/banners/banner4.jpg',
      thumbnail: '/images_v1/projects/collaborations/italamp/thumbnails/collabs4.jpg',
      images: [
        '/images_v1/projects/collaborations/italamp/images/023 Corridor (18).jpg',
        '/images_v1/projects/collaborations/italamp/images/023 Corridor (19).jpg',
        '/images_v1/projects/collaborations/italamp/images/023 Corridor (31).jpg',
        '/images_v1/projects/collaborations/italamp/images/IMG_6656.jpg',
        '/images_v1/projects/collaborations/italamp/images/IMG_6665.jpg',
      ],
      slug: 'italamp',
      category: 'Collaborations'
    },
    // { 
    //   title: 'Eco-Friendly Office Space', 
    //   type: 'Design',
    //   completion_date: '2019-10-05',
    //   architects: ['Zaher Bissar', 'Laura White'],
    //   year: 2019,
    //   location: 'Berlin, Germany',
    //   description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`,
    //    banner:'/images/innerhero/projectdetails.webp',
    //   thumbnail: '/images_v1/projects/collaborations/thumbnails/collabs1.jpg',
    //   images: [
    //     '/images_v1/projects/collaborations/images/image.webp',
    //     '/images_v1/projects/collaborations/images/image.webp',
    //     '/images_v1/projects/collaborations/images/image.webp',
    //     '/images_v1/projects/collaborations/images/image.webp',
    //     '/images_v1/projects/collaborations/images/image.webp',
    //     '/images_v1/projects/collaborations/images/image.webp',
    //     '/images_v1/projects/collaborations/images/image.webp',
    //   ],
    //   client: 'Green Innovators',
    //   slug: 'eco-friendly-office-space',
    //   category: 'Collaborations'
    // },
    // { 
    //   title: 'Modern Residential Tower', 
    //   type: 'Houses',
    //   completion_date: '2018-04-12',
    //   architects: ['Zaher Bissar', 'David Black', 'Sophia Green'],
    //   year: 2018,
    //   location: 'Tokyo, Japan',
    //   description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`,
    //    banner:'/images/innerhero/projectdetails.webp',
    //   thumbnail: '/images_v1/projects/collaborations/thumbnails/collabs2.jpg',
    //   images: [
    //     '/images_v1/projects/collaborations/images/image.webp',
    //     '/images_v1/projects/collaborations/images/image.webp',
    //     '/images_v1/projects/collaborations/images/image.webp',
    //     '/images_v1/projects/collaborations/images/image.webp',
    //     '/images_v1/projects/collaborations/images/image.webp',
    //     '/images_v1/projects/collaborations/images/image.webp',
    //     '/images_v1/projects/collaborations/images/image.webp',
    //   ],
    //   client: 'Tokyo Builders Inc.',
    //   slug: 'modern-residential-tower',
    //   category: 'Collaborations'
    // }
    // { 
    //   title: 'Modern Loft', 
    //   type: 'Living',
    //   completion_date: '2021-04-20',
    //   architects: ['Zaher Bissar'],
    //   year: 2021,
    //   location: 'Seattle, WA',
    //   description : `Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore.`,
    //   banner:'/images/innerhero/projectdetails.webp',
    //   thumbnail: '/images_v1/projects/portfolio/thumbnails/works1.jpg',
    //   images: [
    //     '/images_v1/projects/portfolio/images/image.webp',
    //     '/images_v1/projects/portfolio/images/image.webp',
    //     '/images_v1/projects/portfolio/images/image.webp',
    //     '/images_v1/projects/portfolio/images/image.webp',
    //     '/images_v1/projects/portfolio/images/image.webp',
    //     '/images_v1/projects/portfolio/images/image.webp',
    //     '/images_v1/projects/portfolio/images/image.webp'
    //   ],
    //   client: 'Loft Living Co.',
    //   slug: 'modern-loft',
    //   category: 'Portfolio'
    // },
    // { 
    //   title: 'Seaside Retreat', 
    //   type: 'Houses',
    //   completion_date: '2022-07-12',
    //   architects: ['Zaher Bissar'],
    //   year: 2022,
    //   location: 'Dubai, UAE',
    //   description : `Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore.`,
    //   banner:'/images/innerhero/projectdetails.webp',
    //   thumbnail: '/images_v1/projects/portfolio/thumbnails/works2.jpg',
    //   images: [
    //     '/images_v1/projects/portfolio/images/image.webp',
    //     '/images_v1/projects/portfolio/images/image.webp',
    //     '/images_v1/projects/portfolio/images/image.webp',
    //     '/images_v1/projects/portfolio/images/image.webp',
    //     '/images_v1/projects/portfolio/images/image.webp',
    //     '/images_v1/projects/portfolio/images/image.webp',
    //     '/images_v1/projects/portfolio/images/image.webp',
    //     '/images_v1/projects/portfolio/images/image.webp'
    //   ],
    //   client: 'Beachside Estates',
    //   slug: 'seaside-retreat',
    //   category: 'Portfolio'
    // },
    // { 
    //   id: 9, 
    //   title: 'Penthouse Suite', 
    //   type: 'Houses',
    //   completion_date: '2023-01-10',
    //   architects: ['Zaher Bissar'],
    //   year: 2023,
    //   location: 'Dubai, UAE',
    //   description : `Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore.`,
    //   banner:'/images/innerhero/projectdetails.webp',
    //   thumbnail: '/images_v1/projects/portfolio/thumbnails/works3.jpg',
    //   images: [
    //     '/images_v1/projects/portfolio/images/image.webp',
    //     '/images_v1/projects/portfolio/images/image.webp',
    //     '/images_v1/projects/portfolio/images/image.webp',
    //     '/images_v1/projects/portfolio/images/image.webp',
    //     '/images_v1/projects/portfolio/images/image.webp',
    //     '/images_v1/projects/portfolio/images/image.webp',
    //     '/images_v1/projects/portfolio/images/image.webp',
    //     '/images_v1/projects/portfolio/images/image.webp',
    //     '/images_v1/projects/portfolio/images/image.webp'
    //   ],
    //   client: 'Luxury Living Group',
    //   slug: 'penthouse-suite',
    //   category: 'Portfolio'
    // }
  ];
}