export function getProtfolioProjects() {
  return [
    { 
      id: 1, 
      title: 'The Collector Private Residence', 
      type: 'Design',
      completion_date: '2023-06-15',
      architects: 'Zaher Bissar',
      year: 2020,
      location: 'Riyadh',
      description : `Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore.`,      
      thumbnail: '/images/projects/portfolio/thumbnails/works1.webp',
      images: [
        '/images/projects/portfolio/images/image.webp',
        '/images/projects/portfolio/images/image.webp',
        '/images/projects/portfolio/images/image.webp',
        '/images/projects/portfolio/images/image.webp',
        '/images/projects/portfolio/images/image.webp',
        '/images/projects/portfolio/images/image.webp',
        '/images/projects/portfolio/images/image.webp',
        '/images/projects/portfolio/images/image.webp',
        '/images/projects/portfolio/images/image.webp',
        '/images/projects/portfolio/images/image.webp',
        '/images/projects/portfolio/images/image.webp'
      ],
      client: 'Smith & Co.',
      slug: 'modern-home-design',
      category: 'Portfolio'
    },
    { 
      id: 2, 
      title: 'Luxury Villa', 
      type: 'Houses',
      completion_date: '2022-11-08',
      architects: 'Zaher Bissar',
      year: 2022,
      location: 'Miami, FL',
      description : `Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore.`,
      thumbnail: '/images/projects/portfolio/thumbnails/works2.webp',
      images: [
        '/images/projects/portfolio/images/image.webp',
        '/images/projects/portfolio/images/image.webp',
        '/images/projects/portfolio/images/image.webp',
        '/images/projects/portfolio/images/image.webp',
        '/images/projects/portfolio/images/image.webp',
        '/images/projects/portfolio/images/image.webp',
        '/images/projects/portfolio/images/image.webp',
        '/images/projects/portfolio/images/image.webp'
      ],
      client: 'Doe Enterprises',
      slug: 'luxury-villa',
      category: 'Portfolio'
    },
    { 
      id: 3, 
      title: 'Cozy Interior', 
      type: 'Interior',
      completion_date: '2021-09-23',
      architects: 'Zaher Bissar',
      year: 2021,
      location: 'New York, NY',
      description : `Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore.`,
      thumbnail: '/images/projects/portfolio/thumbnails/works3.webp',
      images: [
        '/images/projects/portfolio/images/image.webp',
        '/images/projects/portfolio/images/image.webp',
        '/images/projects/portfolio/images/image.webp',
        '/images/projects/portfolio/images/image.webp',
        '/images/projects/portfolio/images/image.webp',
        '/images/projects/portfolio/images/image.webp',
        '/images/projects/portfolio/images/image.webp',
        '/images/projects/portfolio/images/image.webp',
        '/images/projects/portfolio/images/image.webp'
      ],
      client: 'Interior Designs LLC',
      slug: 'cozy-interior',
      category: 'Portfolio'
    },
    { 
      id: 4, 
      title: 'Urban Living Room', 
      type: 'Living',
      completion_date: '2020-05-17',
      architects: 'Zaher Bissar',
      year: 2020,
      location: 'Chicago, IL',
      description : `Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore.`,
      thumbnail: '/images/projects/portfolio/thumbnails/works4.webp',
      images: [
        '/images/projects/portfolio/images/image.webp',
        '/images/projects/portfolio/images/image.webp',
        '/images/projects/portfolio/images/image.webp',
        '/images/projects/portfolio/images/image.webp',
        '/images/projects/portfolio/images/image.webp',
        '/images/projects/portfolio/images/image.webp',
        '/images/projects/portfolio/images/image.webp',
        '/images/projects/portfolio/images/image.webp',
        '/images/projects/portfolio/images/image.webp',
        '/images/projects/portfolio/images/image.webp'
      ],
      client: 'Urban Builders',
      slug: 'urban-living-room',
      category: 'Portfolio'
    },
    { 
      id: 5, 
      title: 'Sleek Office Design', 
      type: 'Design',
      completion_date: '2019-12-01',
      architects: 'Zaher Bissar',
      year: 2019,
      location: 'San Francisco, CA',
      description : `Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore.`,
      thumbnail: '/images/projects/portfolio/thumbnails/works5.webp',
      images: [
        '/images/projects/portfolio/images/image.webp',
        '/images/projects/portfolio/images/image.webp',
        '/images/projects/portfolio/images/image.webp',
        '/images/projects/portfolio/images/image.webp',
        '/images/projects/portfolio/images/image.webp',
        '/images/projects/portfolio/images/image.webp',
        '/images/projects/portfolio/images/image.webp',
        '/images/projects/portfolio/images/image.webp',
        '/images/projects/portfolio/images/image.webp',
        '/images/projects/portfolio/images/image.webp',
        '/images/projects/portfolio/images/image.webp'
      ],
      client: 'Tech Innovators',
      slug: 'sleek-office-design',
      category: 'Portfolio'
    },
    { 
      id: 6, 
      title: 'Family Home', 
      type: 'Houses',
      completion_date: '2018-07-29',
      architects: 'Zaher Bissar',
      year: 2018,
      location: 'Austin, TX',
      description : `Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore.`,
      thumbnail: '/images/projects/portfolio/thumbnails/works6.webp',
      images: [
        '/images/projects/portfolio/images/image.webp',
        '/images/projects/portfolio/images/image.webp',
        '/images/projects/portfolio/images/image.webp',
        '/images/projects/portfolio/images/image.webp',
        '/images/projects/portfolio/images/image.webp',
        '/images/projects/portfolio/images/image.webp',
        '/images/projects/portfolio/images/image.webp',
        '/images/projects/portfolio/images/image.webp',
        '/images/projects/portfolio/images/image.webp',
        '/images/projects/portfolio/images/image.webp'
      ],
      client: 'Home Builders Inc.',
      slug: 'family-home',
      category: 'Portfolio'
    },
    // { 
    //   id: 7, 
    //   title: 'Modern Loft', 
    //   type: 'Living',
    //   completion_date: '2021-04-20',
    //   architects: 'Zaher Bissar',
    //   year: 2021,
    //   location: 'Seattle, WA',
    //   description : `Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore.`,
    //   thumbnail: '/images/projects/portfolio/thumbnails/works1.webp',
    //   images: [
    //     '/images/projects/portfolio/images/image.webp',
    //     '/images/projects/portfolio/images/image.webp',
    //     '/images/projects/portfolio/images/image.webp',
    //     '/images/projects/portfolio/images/image.webp',
    //     '/images/projects/portfolio/images/image.webp',
    //     '/images/projects/portfolio/images/image.webp',
    //     '/images/projects/portfolio/images/image.webp'
    //   ],
    //   client: 'Loft Living Co.',
    //   slug: 'modern-loft',
    //   category: 'Portfolio'
    // },
    // { 
    //   id: 8, 
    //   title: 'Seaside Retreat', 
    //   type: 'Houses',
    //   completion_date: '2022-07-12',
    //   architects: 'Zaher Bissar',
    //   year: 2022,
    //   location: 'Malibu, CA',
    //   description : `Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore.`,
    //   thumbnail: '/images/projects/portfolio/thumbnails/works2.webp',
    //   images: [
    //     '/images/projects/portfolio/images/image.webp',
    //     '/images/projects/portfolio/images/image.webp',
    //     '/images/projects/portfolio/images/image.webp',
    //     '/images/projects/portfolio/images/image.webp',
    //     '/images/projects/portfolio/images/image.webp',
    //     '/images/projects/portfolio/images/image.webp',
    //     '/images/projects/portfolio/images/image.webp',
    //     '/images/projects/portfolio/images/image.webp'
    //   ],
    //   client: 'Beachside Estates',
    //   slug: 'seaside-retreat',
    //   category: 'Portfolio'
    // },
    // { 
    //   id: 9, 
    //   title: 'Penthouse Suite', 
    //   type: 'Interior',
    //   completion_date: '2023-01-10',
    //   architects: 'Zaher Bissar',
    //   year: 2023,
    //   location: 'Dubai, UAE',
    //   description : `Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore.`,
    //   thumbnail: '/images/projects/portfolio/thumbnails/works3.webp',
    //   images: [
    //     '/images/projects/portfolio/images/image.webp',
    //     '/images/projects/portfolio/images/image.webp',
    //     '/images/projects/portfolio/images/image.webp',
    //     '/images/projects/portfolio/images/image.webp',
    //     '/images/projects/portfolio/images/image.webp',
    //     '/images/projects/portfolio/images/image.webp',
    //     '/images/projects/portfolio/images/image.webp',
    //     '/images/projects/portfolio/images/image.webp',
    //     '/images/projects/portfolio/images/image.webp'
    //   ],
    //   client: 'Luxury Living Group',
    //   slug: 'penthouse-suite',
    //   category: 'Portfolio'
    // }
  ];
}
export function getPortfolioProjectBySlug(slug) {
  let projects = getProtfolioProjects();
  return projects.find(project => project.slug === slug);
}