export function getProtfolioProjects() {
  return [
    { 
      id: 1, 
      title: 'The Art Collector Private Residence', 
      type: 'Private Residence',
      architects: ['Zaher Bissar'],
      year: 2022,
      location: 'Riyadh',
      description : `One of the first assignments for us is to set the inspiration for the project; we invest a tremendous amount of time seeking inspiration from our client’s lifestyle and personal tastes. Aware of our client’s interest in fine art, we have selected masterpieces from the most prestigious galleries in the world. The warm and textured wooden high walls has created the perfect background for these art pieces.
This project with fortunate high ceilings was transformed into a hidden museum in a private home.`,      
      banner:'/images/projects/portfolio/the_collector_private_residence/banners/banner1.webp',
      thumbnail: '/images/projects/portfolio/the_collector_private_residence/thumbnails/works1.webp',
      images: [
        '/images/projects/portfolio/the_collector_private_residence/images/Rectangle 7.webp',
        '/images/projects/portfolio/the_collector_private_residence/images/Rectangle 113.webp',
        '/images/projects/portfolio/the_collector_private_residence/images/Rectangle 11.webp',
        '/images/projects/portfolio/the_collector_private_residence/images/Rectangle 9.webp',
        '/images/projects/portfolio/the_collector_private_residence/images/Rectangle 114.webp',
        '/images/projects/portfolio/the_collector_private_residence/images/Rectangle 121.webp',
        '/images/projects/portfolio/the_collector_private_residence/images/Rectangle 116.webp',
        '/images/projects/portfolio/the_collector_private_residence/images/Rectangle 117.webp',
        '/images/projects/portfolio/the_collector_private_residence/images/Rectangle 118.webp',
        '/images/projects/portfolio/the_collector_private_residence/images/Rectangle 119.webp',
        '/images/projects/portfolio/the_collector_private_residence/images/Rectangle 120.webp',
        '/images/projects/portfolio/the_collector_private_residence/images/Rectangle 12.webp',
        '/images/projects/portfolio/the_collector_private_residence/images/Rectangle 123.webp',
        '/images/projects/portfolio/the_collector_private_residence/images/Rectangle 124.webp',
        '/images/projects/portfolio/the_collector_private_residence/images/Rectangle 125.webp',
        '/images/projects/portfolio/the_collector_private_residence/images/Rectangle 126.webp',
        '/images/projects/portfolio/the_collector_private_residence/images/Rectangle 14.webp',
        '/images/projects/portfolio/the_collector_private_residence/images/Rectangle 16.webp',
        '/images/projects/portfolio/the_collector_private_residence/images/Rectangle 130.webp',
        '/images/projects/portfolio/the_collector_private_residence/images/Rectangle 129.webp',
        '/images/projects/portfolio/the_collector_private_residence/images/Rectangle 13.webp',
        '/images/projects/portfolio/the_collector_private_residence/images/Rectangle 127.webp',
        '/images/projects/portfolio/the_collector_private_residence/images/Rectangle 15.webp',
        '/images/projects/portfolio/the_collector_private_residence/images/Rectangle 10.webp',
      ],
      client: 'Private',
      slug: 'the-art-collector-private-residence',
      category: 'Portfolio'
    },
    { 
      id: 2, 
      title: 'Al Rawda Reception Villa', 
      type: 'Family Home',
      architects: ['Zaher Bissar'],
      year: 2020,
      location: 'Riyadh',
      description : `This gorgeous 1270 m² project in Riyadh is the family reception villa that makes part of an extensive private complex.
    It is a beautiful example of a luxury contemporary home, infused with Islamic influences that resonate with its vibrant heritage. Original orientalism paintings, crafted antiques, Islamic patterns and intricate noble materials accentuate the identity of the place.`,
      banner:'/images/projects/portfolio/al_rawda_reception_villa/banners/banner2.webp',
      thumbnail: '/images/projects/portfolio/al_rawda_reception_villa/thumbnails/works2.webp',
      images: [
        '/images/projects/portfolio/al_rawda_reception_villa/images/Rectangle 17.webp',
        '/images/projects/portfolio/al_rawda_reception_villa/images/Rectangle 194.webp',
        '/images/projects/portfolio/al_rawda_reception_villa/images/Rectangle 131.webp',
        '/images/projects/portfolio/al_rawda_reception_villa/images/Rectangle 132.webp',
        '/images/projects/portfolio/al_rawda_reception_villa/images/Rectangle 18.webp',
        '/images/projects/portfolio/al_rawda_reception_villa/images/Rectangle 133.webp',
        '/images/projects/portfolio/al_rawda_reception_villa/images/Rectangle 25.webp',
        '/images/projects/portfolio/al_rawda_reception_villa/images/Rectangle 136.webp',
        '/images/projects/portfolio/al_rawda_reception_villa/images/Rectangle 19.webp',
        '/images/projects/portfolio/al_rawda_reception_villa/images/Rectangle 135.webp',
        '/images/projects/portfolio/al_rawda_reception_villa/images/Rectangle 195.webp',
        '/images/projects/portfolio/al_rawda_reception_villa/images/Rectangle 196.webp',
        '/images/projects/portfolio/al_rawda_reception_villa/images/Rectangle 197.webp',
        '/images/projects/portfolio/al_rawda_reception_villa/images/Rectangle 198.webp',
        '/images/projects/portfolio/al_rawda_reception_villa/images/Rectangle 199.webp',
        '/images/projects/portfolio/al_rawda_reception_villa/images/Rectangle 21.webp',
        '/images/projects/portfolio/al_rawda_reception_villa/images/Rectangle 24.webp',
        '/images/projects/portfolio/al_rawda_reception_villa/images/Rectangle 20.webp',
        '/images/projects/portfolio/al_rawda_reception_villa/images/Rectangle 22.webp',
        '/images/projects/portfolio/al_rawda_reception_villa/images/Rectangle 137.webp',
        '/images/projects/portfolio/al_rawda_reception_villa/images/Rectangle 138.webp',
        '/images/projects/portfolio/al_rawda_reception_villa/images/Rectangle 139.webp',
        '/images/projects/portfolio/al_rawda_reception_villa/images/Rectangle 140.webp',
        '/images/projects/portfolio/al_rawda_reception_villa/images/Rectangle 141.webp',
        '/images/projects/portfolio/al_rawda_reception_villa/images/Rectangle 142.webp',
        '/images/projects/portfolio/al_rawda_reception_villa/images/Rectangle 143.webp',
        '/images/projects/portfolio/al_rawda_reception_villa/images/Rectangle 144.webp',
        '/images/projects/portfolio/al_rawda_reception_villa/images/Rectangle 145.webp',
      ],
      client: 'Private',
      slug: 'al-rawda-private-residence',
      category: 'Portfolio'
    },
    { 
      id: 3, 
      title: 'Al Ghadir Villa', 
      type: 'Family Home',
      architects: ['Zaher Bissar'],
      year: 2019,
      description:'The exclusive interior design of this spacious project that impresses with the elegance and splendor of the timeless furniture pieces is the reception area of this villa. The focal point of this project is a double height space, where a crystal light installation from floor to ceiling is stretching out from floor to ceiling. This piece is called the “Crystal Biosphere”',
      location: 'Riyadh',
      banner:'/images/projects/portfolio/al_ghadir_villa/banners/banner3.webp',
      thumbnail: '/images/projects/portfolio/al_ghadir_villa/thumbnails/works3.webp',
      images: [
        '/images/projects/portfolio/al_ghadir_villa/images/Rectangle 27.webp',
        '/images/projects/portfolio/al_ghadir_villa/images/Rectangle 28.webp',
        '/images/projects/portfolio/al_ghadir_villa/images/Rectangle 30.webp',
        '/images/projects/portfolio/al_ghadir_villa/images/Rectangle 29.webp',
        '/images/projects/portfolio/al_ghadir_villa/images/Rectangle 147.webp',
        '/images/projects/portfolio/al_ghadir_villa/images/Rectangle 32.webp',
        '/images/projects/portfolio/al_ghadir_villa/images/Rectangle 31.webp',
        '/images/projects/portfolio/al_ghadir_villa/images/Rectangle 148.webp',
        '/images/projects/portfolio/al_ghadir_villa/images/Rectangle 149.webp',
        '/images/projects/portfolio/al_ghadir_villa/images/Rectangle 150.webp',
        '/images/projects/portfolio/al_ghadir_villa/images/Rectangle 34.webp',
        '/images/projects/portfolio/al_ghadir_villa/images/Rectangle 151.webp',
        '/images/projects/portfolio/al_ghadir_villa/images/Rectangle 152.webp',
        '/images/projects/portfolio/al_ghadir_villa/images/Rectangle 37.webp',
        '/images/projects/portfolio/al_ghadir_villa/images/Rectangle 153.webp',
        '/images/projects/portfolio/al_ghadir_villa/images/Rectangle 154.webp',
        '/images/projects/portfolio/al_ghadir_villa/images/Rectangle 156.webp',
        '/images/projects/portfolio/al_ghadir_villa/images/Rectangle 155.webp',
        '/images/projects/portfolio/al_ghadir_villa/images/Rectangle 200.webp',
        '/images/projects/portfolio/al_ghadir_villa/images/Rectangle 157.webp',
        '/images/projects/portfolio/al_ghadir_villa/images/Rectangle 158.webp',
        '/images/projects/portfolio/al_ghadir_villa/images/Rectangle 159.webp',
        '/images/projects/portfolio/al_ghadir_villa/images/Rectangle 35.webp',
        '/images/projects/portfolio/al_ghadir_villa/images/Rectangle 39.webp',
      ],
      client: 'Private',
      slug: 'al-ghadir-villa',
      category: 'Portfolio'
    },
    { 
      id: 4, 
      title: 'Al Rawda Private Residence', 
      type: 'Family Home',
      architects: ['Zaher Bissar'],
      year: 2021,
      location: 'Riyadh',
      description: 'This luxury private suite combines exquisite, complex detail work with statement prints and muted walls for a modern Asian inspired aesthetic. Three different wallpapers by “De Gournay” are the catchiest elements in this project. Once again, we went in search of the top furniture brands and unique pieces from different European Galleries. A rich color palette is used throughout, giving a sense of depth to the contemporary space; while accent colors and gold hues add a warm splash of color into the design.',
      banner:'/images/projects/portfolio/al_rawda_private_residence/banners/banner4.webp',
      thumbnail: '/images/projects/portfolio/al_rawda_private_residence/thumbnails/works4.webp',
      images: [
        '/images/projects/portfolio/al_rawda_private_residence/images/Rectangle 43.webp',
        '/images/projects/portfolio/al_rawda_private_residence/images/Rectangle 40.webp',
        '/images/projects/portfolio/al_rawda_private_residence/images/Rectangle 45.webp',
        '/images/projects/portfolio/al_rawda_private_residence/images/Rectangle 160.webp',
        '/images/projects/portfolio/al_rawda_private_residence/images/Rectangle 41.webp',
        '/images/projects/portfolio/al_rawda_private_residence/images/Rectangle 42.webp',
        '/images/projects/portfolio/al_rawda_private_residence/images/Rectangle 161.webp',
        '/images/projects/portfolio/al_rawda_private_residence/images/Rectangle 49.webp',
        '/images/projects/portfolio/al_rawda_private_residence/images/Rectangle 46.webp',
        '/images/projects/portfolio/al_rawda_private_residence/images/Rectangle 162.webp',
        '/images/projects/portfolio/al_rawda_private_residence/images/Rectangle 44.webp',
        '/images/projects/portfolio/al_rawda_private_residence/images/Rectangle 47.webp',
        '/images/projects/portfolio/al_rawda_private_residence/images/Rectangle 164.webp',
        '/images/projects/portfolio/al_rawda_private_residence/images/Rectangle 165.webp',
        '/images/projects/portfolio/al_rawda_private_residence/images/Rectangle 166.webp',
        '/images/projects/portfolio/al_rawda_private_residence/images/Rectangle 163.webp',
      ],
      client: 'Private',
      slug: 'al-rawda-private-residence',
      category: 'Portfolio'
    },
    { 
      id: 5, 
      title: 'The Sisters Villa', 
      type: 'Design',
      architects: ['Zaher Bissar'],
      year: 2018,
      location: 'Riyadh',
      description:"From the first meeting the three sisters had a clear vision in mind: a stylish place that challenges the norms of residential design. The handsome style is a perfect blend of Luxury Contemporary and Urban Chic where plain walls and smart fabrics set the mood of the space. They are all tied together with one-of-a- kind furniture pieces and statement artworks. The ensemble aligns perfectly with the homeowner’s vision, taste and lifestyle. Have a look!",
      banner:'/images/projects/portfolio/the_sisters_villa/banners/banner5.webp',
      thumbnail: '/images/projects/portfolio/the_sisters_villa/thumbnails/works5.webp',
      images: [
        '/images/projects/portfolio/the_sisters_villa/images/Rectangle 50.webp',
        '/images/projects/portfolio/the_sisters_villa/images/Rectangle 51.webp',
        '/images/projects/portfolio/the_sisters_villa/images/Rectangle 53.webp',
        '/images/projects/portfolio/the_sisters_villa/images/Rectangle 54.webp',
        '/images/projects/portfolio/the_sisters_villa/images/Rectangle 56.webp',
        '/images/projects/portfolio/the_sisters_villa/images/Rectangle 168.webp',
        '/images/projects/portfolio/the_sisters_villa/images/Rectangle 59.webp',
        '/images/projects/portfolio/the_sisters_villa/images/Rectangle 169.webp',
        '/images/projects/portfolio/the_sisters_villa/images/Rectangle 55.webp',
        '/images/projects/portfolio/the_sisters_villa/images/Rectangle 56.webp',
        '/images/projects/portfolio/the_sisters_villa/images/Rectangle 170.webp',
        '/images/projects/portfolio/the_sisters_villa/images/Rectangle 57.webp',
        '/images/projects/portfolio/the_sisters_villa/images/Rectangle 60.webp',
        '/images/projects/portfolio/the_sisters_villa/images/Rectangle 171.webp',
        '/images/projects/portfolio/the_sisters_villa/images/Rectangle 58.webp',
        '/images/projects/portfolio/the_sisters_villa/images/Rectangle 172.webp',
        '/images/projects/portfolio/the_sisters_villa/images/Rectangle 173.webp',
      ],
      client: 'Private',
      slug: 'the-sisters-villa',
      category: 'Portfolio'
    },
    { 
      id: 6, 
      title: 'Jenadriah Ranch', 
      type: 'Pool House',
      architects: ['Zaher Bissar'],
      year: 2022,
      location: 'Riyadh',
      description:'Layered Textures, earthy tones, hints of sleek patterns and crochet accents with a bold natural wood are just what you need for achieving a Boho-Chic look. The focal point is a wooden backdrop versus expansive glass walls overlooking the pool and its green surrounding. This pool house is a free-standing building in the middle of an extensive green area; This ranch is located in Jenadriah, a suburb of Riyadh city.',
      banner:'/images/projects/portfolio/jenadriah_ranch/banners/banner6.webp',
      thumbnail: '/images/projects/portfolio/jenadriah_ranch/thumbnails/works6.webp',
      images: [
        '/images/projects/portfolio/jenadriah_ranch/images/Rectangle 62.webp',
        '/images/projects/portfolio/jenadriah_ranch/images/Rectangle 63.webp',
        '/images/projects/portfolio/jenadriah_ranch/images/Rectangle 65.webp',
        '/images/projects/portfolio/jenadriah_ranch/images/Rectangle 64.webp',
        '/images/projects/portfolio/jenadriah_ranch/images/Rectangle 178.webp',
        '/images/projects/portfolio/jenadriah_ranch/images/Rectangle 66.webp',
        '/images/projects/portfolio/jenadriah_ranch/images/Rectangle 176.webp',
        '/images/projects/portfolio/jenadriah_ranch/images/Rectangle 67.webp',
        '/images/projects/portfolio/jenadriah_ranch/images/Rectangle 174.webp',
        '/images/projects/portfolio/jenadriah_ranch/images/Rectangle 177.webp',
      ],
      client: 'Private',
      slug: 'jenadriah_ranch',
      category: 'Portfolio'
    },
    // { 
    //   id: 7, 
    //   title: 'Modern Loft', 
    //   type: 'Living',
    //   completion_date: '2021-04-20',
    //   architects: ['Zaher Bissar'],
    //   year: 2021,
    //   location: 'Seattle, WA',
    //   description : `Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore.`,
    //   banner:'/images/innerhero/projectdetails.webp',
    //   thumbnail: '/images/projects/portfolio/thumbnails/works1.webp',
    //   images: [
    //     '/images/projects/portfolio/images/image.webp',
    //     '/images/projects/portfolio/images/image.webp',
    //     '/images/projects/portfolio/images/image.webp',
    //     '/images/projects/portfolio/images/image.webp',
    //     '/images/projects/portfolio/images/image.webp',
    //     '/images/projects/portfolio/images/image.webp',
    //     '/images/projects/portfolio/images/image.webp'
    //   ],
    //   client: 'Loft Living Co.',
    //   slug: 'modern-loft',
    //   category: 'Portfolio'
    // },
    // { 
    //   id: 8, 
    //   title: 'Seaside Retreat', 
    //   type: 'Houses',
    //   completion_date: '2022-07-12',
    //   architects: ['Zaher Bissar'],
    //   year: 2022,
    //   location: 'Dubai, UAE',
    //   description : `Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore.`,
    //   banner:'/images/innerhero/projectdetails.webp',
    //   thumbnail: '/images/projects/portfolio/thumbnails/works2.webp',
    //   images: [
    //     '/images/projects/portfolio/images/image.webp',
    //     '/images/projects/portfolio/images/image.webp',
    //     '/images/projects/portfolio/images/image.webp',
    //     '/images/projects/portfolio/images/image.webp',
    //     '/images/projects/portfolio/images/image.webp',
    //     '/images/projects/portfolio/images/image.webp',
    //     '/images/projects/portfolio/images/image.webp',
    //     '/images/projects/portfolio/images/image.webp'
    //   ],
    //   client: 'Beachside Estates',
    //   slug: 'seaside-retreat',
    //   category: 'Portfolio'
    // },
    // { 
    //   id: 9, 
    //   title: 'Penthouse Suite', 
    //   type: 'Houses',
    //   completion_date: '2023-01-10',
    //   architects: ['Zaher Bissar'],
    //   year: 2023,
    //   location: 'Dubai, UAE',
    //   description : `Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore.`,
    //   banner:'/images/innerhero/projectdetails.webp',
    //   thumbnail: '/images/projects/portfolio/thumbnails/works3.webp',
    //   images: [
    //     '/images/projects/portfolio/images/image.webp',
    //     '/images/projects/portfolio/images/image.webp',
    //     '/images/projects/portfolio/images/image.webp',
    //     '/images/projects/portfolio/images/image.webp',
    //     '/images/projects/portfolio/images/image.webp',
    //     '/images/projects/portfolio/images/image.webp',
    //     '/images/projects/portfolio/images/image.webp',
    //     '/images/projects/portfolio/images/image.webp',
    //     '/images/projects/portfolio/images/image.webp'
    //   ],
    //   client: 'Luxury Living Group',
    //   slug: 'penthouse-suite',
    //   category: 'Portfolio'
    // }
  ];
}

export function getPortfolioProjectBySlug(slug) {
  let projects = getProtfolioProjects();
  return projects.find(project => project.slug === slug);
}

export function getCollabsProjects() {
  return [
    { 
      id: 1, 
      title: 'De Gournay', 
      type: 'Design',
      architects: ['Zaher Bissar', 'Others'],
      year: 2023,
      location: 'Dubai, UAE',
      banner:'/images/projects/collaborations/de_gournay/banners/banner1.webp',
      thumbnail: '/images/projects/collaborations/de_gournay/thumbnails/collabs1.webp',
      images: [
        '/images/projects/collaborations/de_gournay/images/Rectangle 68.webp',
        '/images/projects/collaborations/de_gournay/images/Rectangle 77.webp',
        '/images/projects/collaborations/de_gournay/images/Rectangle 72.webp',
        '/images/projects/collaborations/de_gournay/images/Rectangle 71.webp',
        '/images/projects/collaborations/de_gournay/images/Rectangle 94.webp',
        '/images/projects/collaborations/de_gournay/images/Rectangle 95.webp',
        '/images/projects/collaborations/de_gournay/images/Rectangle 96.webp',
        '/images/projects/collaborations/de_gournay/images/Rectangle 73.webp',
        '/images/projects/collaborations/de_gournay/images/Rectangle 74.webp',
        '/images/projects/collaborations/de_gournay/images/Rectangle 75.webp',
      ],
      client: 'Art & Co.',
      slug: 'de-gournay',
      category: 'Collaborations'
    },
    { 
      id: 2, 
      title: 'Preciosa', 
      type: 'Interior',
      architects: ['Zaher Bissar', 'Others'],
      year: 2021,
      location: 'Dubai, UAE',
      banner:'/images/projects/collaborations/preciosa/banners/banner3.webp',
      thumbnail: '/images/projects/collaborations/preciosa/thumbnails/collabs3.webp',
      images: [
        '/images/projects/collaborations/preciosa/images/Rectangle 82.webp',
        '/images/projects/collaborations/preciosa/images/Rectangle 77.webp',
        '/images/projects/collaborations/preciosa/images/Rectangle 106.webp',
        '/images/projects/collaborations/preciosa/images/Rectangle 107.webp',
        '/images/projects/collaborations/preciosa/images/Rectangle 201.webp',
        '/images/projects/collaborations/preciosa/images/Rectangle 81.webp',
        '/images/projects/collaborations/preciosa/images/Rectangle 80.webp',
        '/images/projects/collaborations/preciosa/images/Rectangle 111.webp',
        '/images/projects/collaborations/preciosa/images/Rectangle 108.webp',
        '/images/projects/collaborations/preciosa/images/Rectangle 109.webp',
      ],
      client: 'Luxury Stays',
      slug: 'preciosa',
      category: 'Collaborations'
    },    
    { 
      id: 3, 
      title: 'Baccarat', 
      type: 'Houses',
      architects: ['Zaher Bissar', 'Others'],
      year: 2022,
      location: 'Dubai, UAE',
      banner:'/images/projects/collaborations/baccarat/banners/banner2.webp',
      thumbnail: '/images/projects/collaborations/baccarat/thumbnails/collabs2.webp',
      images: [
        '/images/projects/collaborations/baccarat/images/Rectangle 83.webp',
        '/images/projects/collaborations/baccarat/images/Rectangle 84.webp',
        '/images/projects/collaborations/baccarat/images/Rectangle 97.webp',
        '/images/projects/collaborations/baccarat/images/Rectangle 88.webp',
        '/images/projects/collaborations/baccarat/images/Rectangle 98.webp',
        '/images/projects/collaborations/baccarat/images/Rectangle 99.webp',
        '/images/projects/collaborations/baccarat/images/Rectangle 85.webp',
        '/images/projects/collaborations/baccarat/images/Rectangle 87.webp',
        '/images/projects/collaborations/baccarat/images/Rectangle 100.webp',
        '/images/projects/collaborations/baccarat/images/Rectangle 86.webp',
      ],
      client: 'Business Solutions Ltd.',
      slug: 'baccarat',
      category: 'Collaborations'
    },
    { 
      id: 4, 
      title: 'Italamp', 
      type: 'Living',
      architects: ['Zaher Bissar', 'Others'],
      year: 2020,
      location: 'London, UK',
      banner:'/images/projects/collaborations/italamp/banners/banner4.webp',
      thumbnail: '/images/projects/collaborations/italamp/thumbnails/collabs4.webp',
      images: [
        '/images/projects/collaborations/italamp/images/Rectangle 92.webp',
        '/images/projects/collaborations/italamp/images/Rectangle 112.webp',
        '/images/projects/collaborations/italamp/images/Rectangle 90.webp',
        '/images/projects/collaborations/italamp/images/Rectangle 89.webp',
        '/images/projects/collaborations/italamp/images/Rectangle 93.webp',
      ],
      client: 'Urban Developments',
      slug: 'italamp',
      category: 'Collaborations'
    },
    // { 
    //   id: 5, 
    //   title: 'Eco-Friendly Office Space', 
    //   type: 'Design',
    //   completion_date: '2019-10-05',
    //   architects: ['Zaher Bissar', 'Laura White'],
    //   year: 2019,
    //   location: 'Berlin, Germany',
    //   description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`,
    //    banner:'/images/innerhero/projectdetails.webp',
    //   thumbnail: '/images/projects/collaborations/thumbnails/collabs1.webp',
    //   images: [
    //     '/images/projects/collaborations/images/image.webp',
    //     '/images/projects/collaborations/images/image.webp',
    //     '/images/projects/collaborations/images/image.webp',
    //     '/images/projects/collaborations/images/image.webp',
    //     '/images/projects/collaborations/images/image.webp',
    //     '/images/projects/collaborations/images/image.webp',
    //     '/images/projects/collaborations/images/image.webp',
    //   ],
    //   client: 'Green Innovators',
    //   slug: 'eco-friendly-office-space',
    //   category: 'Collaborations'
    // },
    // { 
    //   id: 6, 
    //   title: 'Modern Residential Tower', 
    //   type: 'Houses',
    //   completion_date: '2018-04-12',
    //   architects: ['Zaher Bissar', 'David Black', 'Sophia Green'],
    //   year: 2018,
    //   location: 'Tokyo, Japan',
    //   description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`,
    //    banner:'/images/innerhero/projectdetails.webp',
    //   thumbnail: '/images/projects/collaborations/thumbnails/collabs2.webp',
    //   images: [
    //     '/images/projects/collaborations/images/image.webp',
    //     '/images/projects/collaborations/images/image.webp',
    //     '/images/projects/collaborations/images/image.webp',
    //     '/images/projects/collaborations/images/image.webp',
    //     '/images/projects/collaborations/images/image.webp',
    //     '/images/projects/collaborations/images/image.webp',
    //     '/images/projects/collaborations/images/image.webp',
    //   ],
    //   client: 'Tokyo Builders Inc.',
    //   slug: 'modern-residential-tower',
    //   category: 'Collaborations'
    // }
  ];
}

export function getCollabsProjectBySlug(slug) {
  let projects = getCollabsProjects();
  return projects.find(project => project.slug === slug);
}

export function getEditorial() {
  return [
    { 
      title: 'Editorial Art Gallery', 
      image:'/images/editorial/images/Rectangle 183.webp',
    },         
    { 
      title: 'Editorial Art Gallery', 
      image:'/images/editorial/images/Rectangle 180.webp',
    },
    { 
      title: 'Editorial Art Gallery', 
      image:'/images/editorial/images/Rectangle 181.webp',
    },    
    { 
      title: 'Editorial Art Gallery', 
      image:'/images/editorial/images/Rectangle 182.webp',
    },    
    // { 
    //   title: 'Editorial Art Gallery', 
    //   image:'/images/editorial/images/Rectangle 03_Resized.webp',
    // },  
    { 
      title: 'Editorial Art Gallery', 
      image:'/images/editorial/images/Rectangle 184.webp',
    },     
    { 
      title: 'Editorial Art Gallery', 
      image:'/images/editorial/images/Rectangle 185.webp',
    },      
    { 
      title: 'Editorial Art Gallery', 
      image:'/images/editorial/images/Rectangle 186.webp',
    },     
    { 
      title: 'Editorial Art Gallery', 
      image:'/images/editorial/images/Rectangle 187.webp',
    }, 
    { 
      title: 'Editorial Art Gallery', 
      image:'/images/editorial/images/Rectangle 188.webp',
    },     
    { 
      id: 10, 
      title: 'Editorial Art Gallery', 
      image:'/images/editorial/images/Rectangle 189.webp',
    },    
    { 
      title: 'Editorial Art Gallery', 
      image:'/images/editorial/images/Rectangle 190.webp',
    },   
    { 
      title: 'Editorial Art Gallery', 
      image:'/images/editorial/images/Rectangle 191.webp',
    },     
    { 
      title: 'Editorial Art Gallery', 
      image:'/images/editorial/images/Rectangle 192.webp',
    },     
    { 
      title: 'Editorial Art Gallery', 
      image:'/images/editorial/images/Rectangle 193.webp',
    },
    // { 
    //   title: 'Editorial Art Gallery', 
    //   image:'/images/editorial/images/Rectangle 16_Resized.webp',
    // },
  ]
}

export function getAccordion() {
  return [
    { 
      id: 1, 
      title: 'The creative mind', 
      content: 'Armed with boundless creativity and an unwavering passion for interior design, Zaher Bissar embarked on a journey back in 2014, founding Bissar Concepts. His commitment to crafting spaces that echo an artistic vision and a relentless pursuit of beauty has captivated clients and admirers alike. Bissar Concept’s portfolio grew, each project bearing the imprint of its unique design. With time, what began as a solitary venture evolved into a thriving interior design company, reflecting the intricate charm of interior design.'
    },
    { 
      id: 2, 
      title: 'Our Story', 
      content: 'Currently situated in Riyadh, with a strong presence in Beirut, Bissar Concepts is the epitome of sophisticated living. Having extended its influence across the region, the luxury atelier holds hundreds of projects spanning across KSA, UAE, the Levant, and Egypt. Bissar Concepts offers a world of bespoke luxury, ranging from intricate architectural refinement to customized design, where every space is meticulously curated to illustrate elegance and refinement. Our studio fully integrates interior design services specialized in upscale projects including palaces, private residences, public buildings, corporate offices, and hotels.'
    },    
    { 
      id: 3, 
      title: 'Our Approach', 
      content: 'By taking a fresh approach to design, we create viable and dynamic spaces that are as unique as the individuality of each of our clients. Our work ranges from minimalism to classicism, with luxury contemporary defining most of our projects. We aim to consistently reflect the timeless elegance of classical aesthetics, but also introduce tradition with a modern flair.'
    },    
    { 
      id: 4, 
      title: 'Our Philosophy', 
      content: 'Authenticity, individuality, and innovation are the cornerstone of every project we undertake. Our work is designed to blend aesthetics with functionality, seamlessly integrating the aspirations and lifestyles of our clients into every detail with finesse and a focus on well-being. Drawing inspiration from light, nature, and the art of equilibrium, our interior architecture serves as the foundation of our conceptual framework. Meanwhile, the essence of our philosophy is defined by the use of noble materials, luxurious detailing, and refined design. Our mission transcends the ordinary, aiming to orchestrate immersive experiences that captivate the senses: mentally by adding elements of surprise, spiritually by stimulating tranquillity, and culturally by infusing art and history.'
    }
  ]
}
